### ISSUE TITLE
change test runner to ava and enzyme

### ISSUE THREAD

**Issue by carloscuatin** [Hashnode/mern-starter#143]
lately I've explored the test runner avajs and it seems rather better than mocha, there is an option to explore it? step include enzyme?

**Comment by somus** [comment]
@carloscuatin I've pushed the file structure changes. Earlier today, I saw your tweet. It's great that you started on implementing ava. :) Could you pull the v2.0.0 and continue working? It will be easier for you merge now than later.

**Comment by carloscuatin** [comment]
@somus of course today finished implementing server tests

**Comment by somus** [comment]
Hey @carloscuatin, how is ava implementation going? Could you include code coverage along with it too?

**Comment by carloscuatin** [comment]
@somus if I send the changes as soon as possible and everything is ready

**Comment by carloscuatin** [comment]
apologies week was very hard and could not send the PR but I'm preparing good vibes

**Comment by sandeeppanda92** [comment]
@carloscuatin Hey Carlos! Hope you are doing good. Can you please give us an update on this? We are looking to release v2.0 towards end of this week (or early next week). If you can let us know the status, it'll be great! 

In case you don't have much time, may be @somus can help you and finish this over the weekends (so that the release is not delayed).

**Comment by carloscuatin** [comment]
@sandeeppanda92 quiet before the end of this week sends the update

**Comment by somus** [comment]
Completed in v2.0.0 branch.
