### ISSUE TITLE
FOUC on startup

### ISSUE THREAD

**Issue by Stalso** [Hashnode/mern-starter#161]
Hello. I am exploring your v2 branch. And I noticed, that you have [FOUC effect](https://en.wikipedia.org/wiki/Flash_of_unstyled_content) on page loading in development mode. As far, as I understand `css-modules-require-hook` injects only correct class names, not css. How can I overcome this and how do overcome this in production?

**Comment by kandros** [comment]
development: the css is injected by webpack as blobs ( the css is just in memory), you can see as link tags appearing after the FOUC effect 
production:  a css file is created and a link tag is inserted in the page at server rendering time [see here](https://github.com/Hashnode/mern-starter/blob/v2.0.0/server/server.js#L74)

No idea how to prevent it in development but in production is not present.

**Comment by somus** [comment]
To make the hot reloading of CSS work, we are not extracting CSS in development. Ideally, during server rendering, we will be extracting CSS, and we will get a .css file, and we can use it in the html template. That's what we are doing in production.

In development, after all scripts get loaded, react loads the CSS as BLOBs. That's why there is a second of FOUC in development.

FOUC is a caveat of using server rendering and hot reloading together. I've added a caveat section in README.
