### ISSUE TITLE
Running on dev drops warning on console

### ISSUE THREAD

**Issue by CoericK** [Hashnode/mern-starter#173]
Just made a clean clone, and `npm install` then `npm start` and the app seems to run fine but on console drops this message:

```
warning.js?8a56:44 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) <!-- react-empty: 1 -
 (server) <div data-reactroot="
```

**Comment by somus** [comment]
This is already documented in caveat section of the readme. It occurs due to hash mismatch in react-router. We have to use `match` from react-router to fix this warning But, if we use `match`, `react-hot-reloader` stops working. That's why we decided to leave the warning.

It is just a warning. It doesn't do any harm.
