### ISSUE TITLE
Add webpack resolve alias?

### ISSUE THREAD

**Issue by adriaanbalt** [Hashnode/mern-starter#286]
I tried to add aliases to the dev webpack configuration so the JS paths would be easier to maintain.  Unfortunately this isn't working.  I have used this across various other webpack React projects.  Do you happen to know why that wouldn't work within this project?

For example:
```
  resolve: {
    extensions: ['', '.js', '.jsx'],
    modules: [
      'client',
      'node_modules',
    ],
    alias: {
      Client: path.resolve(__dirname, 'client')
    }
  },
```

**Comment by adriaanbalt** [comment]
this may be due to webpack itself.

**Comment by epilande** [comment]
Hi @adriaanbalt I'm also running into this problem.. I believe it's due to the way SSR is set up.
I haven't tried this yet, but maybe this babel plugin would help https://github.com/tleunen/babel-plugin-module-resolver. You could try adding it here https://github.com/Hashnode/mern-starter/blob/master/index.js#L13

**Comment by adriaanbalt** [comment]
Thanks, that worked @epilande
