### ISSUE TITLE
Component files named index.jsx

### ISSUE THREAD

**Issue by nicgordon** [Hashnode/mern-starter#74]
Just a thought I had that I wanted to put up for discussion:
Currently, to import a component from another file you have to do something like `'./container/PostContainer/PostContainer';` and the second PostContainer seems a bit redundant. Inside our component and container folders we have the component itself named `index.jsx`. This is so that we are able to simply import that file from around the application by going `import PostContainer from './container/PostContainer';` which reads much nicer.

**Comment by carloscuatin** [comment]
It is something interesting but always complicates things because if we leave a index.js will detect complex in editors when searching the file for editing and remove the folders is not a good idea because what is sought is to separate each container your css or configuration files needed without seeing scattered in the container folder

**Comment by somus** [comment]
As @carloscuatin expressed, it can become difficult with IDEs if we name those files index.jsx. Both ways has their advantages and disadvantages. We can continue the discussion at #90.
